print("=" * 40)
print(f"Summary Salary" .center(40))
print("=" * 40)
print()
num1 = input("Enter the salary : ")
num1 = float(num1)
num2 = input("Enter the % bonus : ")
num2 = float(num2)
bonus = num1 * (num2 / 100)
summary = num1 + bonus
print("=" * 40)
print(f"Salary = {num1:,.2f} " .center(40))
print(f"Bonus = {bonus:,.2f}" .center(40))
print(f"Summary = {summary:,.2f}" .center(40))
print("=" * 40)
